# This is a sample build configuration for Java (Maven).
# Check our guides at https://confluence.atlassian.com/x/zd-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: maven:3.6.1

pipelines:
  branches:
    master:
      - step:
          name: Build Petclinic
          caches:
            - maven
          script:
            - export DAY_OF_YEAR="$(date +%j)"
            - export TWO_DIGIT_YEAR="$(date +%y)"
            - export TIME="$(date +%H%M%S)"
            - export GENERATED_VERSION=$Major.$Minor.$TWO_DIGIT_YEAR$DAY_OF_YEAR.$TIME
            - printenv | grep GENERATED_VERSION > environment.txt
            - mvn -B verify -DskipTests -Dproject.versionNumber=$GENERATED_VERSION # -B batch mode makes Maven less verbose
          artifacts:
          - environment.txt
          - "target/*.war"
      - step:
          name: Package Flyway
          script:
            # Read $GENERATED_VERSION
            - while IFS='' read -r line || [[ -n "$line" ]]; do export $line; done < environment.txt
            - pipe: octopusdeploy/pack:0.6.0
              variables:
                ID: petclinic.mysql.flyway
                FORMAT: 'Nupkg'
                VERSION: $GENERATED_VERSION
                SOURCE_PATH: 'flyway'
                OUTPUT_PATH: './flyway'
                DEBUG: 'false'
          artifacts:
            - "flyway/*.nupkg"
      - step:
          name: Push packages
          image: octopusdeploy/octo:7.3.2
          script:
            # Read $GENERATED_VERSION
            - while IFS='' read -r line || [[ -n "$line" ]]; do export $line; done < environment.txt
            - octo push --package "./flyway/petclinic.mysql.flyway.$GENERATED_VERSION.nupkg" --server $OCTOPUS_URL --space 'Bitbucket' --apiKey $OCTOPUS_API_KEY
            - octo push --package "target/petclinic.web.$GENERATED_VERSION.war" --server $OCTOPUS_URL --space 'Bitbucket' --apiKey $OCTOPUS_API_KEY
      - step:
          name: Push Build Info to Octopus
          image: octopusdeploy/octo:7.3.2
          script:
            # Read $GENERATED_VERSION
            - while IFS='' read -r line || [[ -n "$line" ]]; do export $line; done < environment.txt
            - apk update && apk upgrade && apk add --no-cache git curl jq
            - /bin/sh create-build-info.sh $BITBUCKET_REPO_OWNER $BITBUCKET_REPO_SLUG $BITBUCKET_BUILD_NUMBER $BITBUCKET_COMMIT $BITBUCKET_BRANCH $BITBUCKET_GIT_HTTP_ORIGIN
            - octo build-information --package-id 'petclinic.web' --package-id 'petclinic.mysql.flyway' --version $GENERATED_VERSION --file=octopus.buildinfo --server $OCTOPUS_URL --space 'Bitbucket' --apiKey $OCTOPUS_API_KEY 
        