# BitBucket Pipeline file for PetClinic
# 
# Only use spaces to indent the .yml configuration.
# -------
image: maven:3.6.1 

clone:
  enabled: false
pipelines:
  branches: 
    master: 
      - step:
          name: generate version
          script:
            - export GENERATED_VERSION=$MAJOR_VERSION.$MINOR_VERSION."$(date +%y%m%d)"."$(date +%H%M)"
            - printenv | grep GENERATED_VERSION > environment.txt
          artifacts:
          - environment.txt
      - step:
          name: build petclinic
          caches:
            - maven
          clone:
            enabled: true
          script:
            - while IFS='' read -r line || [[ -n "$line" ]]; do export $line; done < environment.txt
            - mvn -B verify -DskipTests -Dproject.versionNumber=$GENERATED_VERSION -DdatabaseUserName=$DatabaseUserName -DdatabaseUserPassword=$DatabaseUserPassword -DdatabaseServerName=$DatabaseServerName -DdatabaseName=$DatabaseName 
          artifacts:
          - environment.txt
          - "target/*.war"
      - step:
          name: octo pack mysql-flyway
          script:
            - while IFS='' read -r line || [[ -n "$line" ]]; do export $line; done < environment.txt
            - pipe: octopusdeploy/octo:0.11.0
              variables:
                CLI_COMMAND: 'pack'
                ID: 'petclinic.mysql.flyway'
                FORMAT: 'Zip'
                VERSION: ${GENERATED_VERSION}
                SOURCE_PATH: 'flyway'
                OUTPUT_PATH: './flyway'
                DEBUG: 'false'
          artifacts:
            - "flyway/*.zip"
      - step:
          name: octo push
          script:
            - while IFS='' read -r line || [[ -n "$line" ]]; do export $line; done < environment.txt
            - pipe: octopusdeploy/octo:0.11.0
              variables:
                CLI_COMMAND: 'push'
                OCTOPUS_SERVER: $OCTOPUS_SERVER
                OCTOPUS_APIKEY: $OCTOPUS_API_KEY
                OCTOPUS_SPACE: $OCTOPUS_SPACE
                PACKAGES: [ "./flyway/petclinic.mysql.flyway.$GENERATED_VERSION.zip", "target/petclinic.web.$GENERATED_VERSION.war" ]
                DEBUG: 'false'
      - step:
          name: octo build-information
          clone:
            enabled: true
          script:
            - while IFS='' read -r line || [[ -n "$line" ]]; do export $line; done < environment.txt
            - pipe: octopusdeploy/octo:0.11.0
              variables:
                CLI_COMMAND: 'build-information'
                OCTOPUS_SERVER: $OCTOPUS_SERVER
                OCTOPUS_APIKEY: $OCTOPUS_API_KEY
                OCTOPUS_SPACE: $OCTOPUS_SPACE
                VERSION: $GENERATED_VERSION
                PACKAGE_IDS: ['petclinic.web']
                MULTIPLE_COMMITS: 'true'
                DEBUG: 'false'
          artifacts:
            - octopus.buildinfo
      - step:
          name: octo create-release
          script:
            - while IFS='' read -r line || [[ -n "$line" ]]; do export $line; done < environment.txt
            - pipe: octopusdeploy/octo:0.11.0
              variables:
                CLI_COMMAND: 'create-release'
                OCTOPUS_SERVER: $OCTOPUS_SERVER
                OCTOPUS_APIKEY: $OCTOPUS_API_KEY
                OCTOPUS_SPACE: $OCTOPUS_SPACE
                PROJECT: $OCTOPUS_PROJECT
                DEBUG: 'false'
      - step:
          name: octo deploy-release
          script:
            - pipe: octopusdeploy/octo:0.11.0
              variables:
                CLI_COMMAND: 'deploy-release'
                OCTOPUS_SERVER: $OCTOPUS_SERVER
                OCTOPUS_APIKEY: $OCTOPUS_API_KEY
                OCTOPUS_SPACE: $OCTOPUS_SPACE
                PROJECT: $OCTOPUS_PROJECT
                RELEASE_NUMBER: 'latest'
                DEPLOY_TO: ['Development']
                DEBUG: 'false'