# BitBucket Pipeline file for PetClinic
# 
# Only use spaces to indent the .yml configuration.
# -------
image: maven:3.6.1 

clone:
  enabled: false 
pipelines:
  branches: 
    run-runbook: 
      - step:
          name: octo run-runbook
          script:
            - pipe: octopusdeploy/octopus-cli-run:0.15.0
              variables:
                CLI_COMMAND: 'run-runbook'
                OCTOPUS_SERVER: $OCTOPUS_SERVER
                OCTOPUS_APIKEY: $OCTOPUS_API_KEY
                OCTOPUS_SPACE: $OCTOPUS_SPACE
                PROJECT: $OCTOPUS_PROJECT
                RUNBOOK: 'Check Database exists'
                ENVIRONMENTS: ['Development']
                PROGRESS: 'true'
                DEBUG: 'false'      