# This is a sample build configuration for Java (Maven).
# Check our guides at https://confluence.atlassian.com/x/zd-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: maven:3.6.1

pipelines:
  default:
    - step:
        name: Build Petclinic
        caches:
          - maven
        script:
          - export VERSION_NUMBER=$Major.$Minor.$TWO_DIGIT_YEAR$DAY_OF_YEAR.$TIME
          - mvn -B verify -DskipTests -Dproject.versionNumber=$VERSION_NUMBER # -B batch mode makes Maven less verbose
        artifacts:
          - "target/*.war"
    - step:
        name: Package Flyway
        script:
          - pipe: octopusdeploy/pack:0.5.1
            variables:
              ID: petclinic.mysql.flyway
              FORMAT: 'Nupkg'
              VERSION: $VERSION_NUMBER
              SOURCE_PATH: 'flyway'
              OUTPUT_PATH: './flyway'
              DEBUG: 'false'
        artifacts:
          - "flyway/*.nupkg"
    - step:
        name: Push packages
        script:
          - export DAY_OF_YEAR="$(date +%j)"
          - export TWO_DIGIT_YEAR="$(date +%y)"
          - export TIME="$(date +%H%M%S)"
          - export BITBUCKET_BUILD_NUMBER=$Major.$Minor.$TWO_DIGIT_YEAR$DAY_OF_YEAR.$TIME
          - octo push --package "./flyway/petclinic.mysql.flyway.$VERSION_NUMBER.nupkg" --server $OCTOPUS_URL --space 'Bitbucket' --apiKey $OCTOPUS_API_KEY
          - octo push --package "target/petclinic.web.$VERSION_NUMBER.war" -- server $OCTOPUS_URL --space 'Bitbucket' --apiKey $OCTOPUS_API_KEY
        image: octopusdeploy/octo:latest

    
